class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/maro/final-projects/Aba-ViTrack'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/home/maro/final-projects/Aba-ViTrack/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/home/maro/final-projects/Aba-ViTrack/pretrained_networks'
        self.lasot_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/lasot'
        self.mtc_aic4_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw'
        self.got10k_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/got10k/train'
        self.got10k_val_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/got10k/val'
        self.lasot_lmdb_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/lasot_lmdb'
        self.got10k_lmdb_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/got10k_lmdb'
        self.trackingnet_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/trackingnet'
        self.trackingnet_lmdb_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/trackingnet_lmdb'
        self.coco_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/coco'
        self.coco_lmdb_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/vid'
        self.imagenet_lmdb_dir = '/media/maro/Mom0-0/Datasets/MTC-AIC/raw/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
